modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/MightyDanp/TechCore/issues"
license="AGPL-3.0 license"

[[mods]]
    modId="techcore"
    logoFile="techcore.png"
    version="0.0.0.1"
    displayName="Tech Core"
    displayURL=""
    authors="MightyDanp"
    description='''A simple but powerful coremod.'''

[[dependencies.techcore]]
    modId="neoforge"
    type="required"
    versionRange="[20.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.techcore]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
   config="techcore.mixins.json"

[[accessTransformers]]
   file="accesstransformer.cfg"